### ISSUE TITLE
Feature: Simple balance transaction command

### ISSUE THREAD

**Issue by ddjerqq** [ddjerqq/Astro#5]
Create Balance transaction command, which will take a User sender object, and a User receiver object, and a decimal Amount parameter. The command will return a boolean, indicating whether or not the transaction was a success.

**Comment by gogodze** [comment]
i'll start this one when the wallet is finished

**Comment by ddjerqq** [comment]
usually when creating commands or queries (CQRS) we do it in the appropriate folder.
for example for this command, you will need to create a folder in the application layer
`src/Application/Economy/Commands/BalanceTransactionCommand.cs` we separate Queries (READ-only operations) and Commands (WRITE, UPDATE, DELETE operations) read up more about `CQRS` topic to find out why we do this.

every request file can have the following:
- the result:
  also a record, containing complex results, if needed.
- the command:
  usually a record - immutable, because commands should not change, from creation to execution.
- the validators:
  an abstract validator using FluentValidation, that validates the properties of the command, to ensure that for example the data - the amount we pass to the balance transaction is a non-zero positive decimal.
  > please keep in mind, the validation is done automatically before any request executes thanks to `ValidationBehaviour.cs`
- the actual handler for this command.
  this will be the class that will handle the execution of this command.

please see [the users folder](https://github.com/ddjerqq/Astro/tree/master/src/Application/Users) in the repo.

please follow the style, and the access modifier conventions we have setup to keep the repo organized and clean.

**Comment by gogodze** [comment]
should commands use mediatr?
